# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HelloThere_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HelloThere_iOS
pod 'NMapsMap'
pod 'Alamofire'
pod 'SwiftyJSON'
pod 'DGCharts'


end
